athena-syntaxe:
  extends: .syntaxe_job_template
  variables:
    CWD: "./athena"

athena-deploy:
  extends: .deploy_job_template
  environment: production_athena
  variables:
    CWD: "./athena"
  needs:
    - job: "athena-syntaxe"

athena-destroy:
  extends: .destroy_job_template
  variables:
    CWD: "./athena"
  needs:
    - job: "athena-syntaxe"
